MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

RGB_MATRIX_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball

CONSOLE_ENABLE = no
VERBOSE = no
COMMAND_ENABLE = no

GRAVE_ESC_ENABLE = yes
