MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_LOCK_ENABLE = no
CAPS_WORD_ENABLE = no

RGB_MATRIX_ENABLE = yes
ENCODER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball

CONSOLE_ENABLE = no
VERBOSE = no
COMMAND_ENABLE = no

GRAVE_ESC_ENABLE = yes

SPACE_CADET_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
